[package]
name = "greeting"
version = "0.1.0"
edition = "2021"

[dependencies]
allocator_api = "0.6.0"
oom = "0.3.0"
program = "0.3.0"
rand = "0.8.3"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
